### ISSUE TITLE
Unable to select display I2C adress in web configurator

### ISSUE THREAD

**Issue by basst22778** [shanteacontrols/OpenDeck#166]
i am trying to chance the i2c adress in the web configurator as discribed in your comment.
https://github.com/shanteacontrols/OpenDeck/issues/28#issuecomment-633228800

There is no option in the interface. (bluepill, V7.3.2)
Is this option already depricated?

**Comment by paradajz** [comment]
Can you post a screenshot?

**Comment by basst22778** [comment]
(url
![Bildschirmfoto 2022-08-22 um 13 10 50](https://user-images.githubusercontent.com/29714593/185916944-ec310a7a-8671-45a9-be0c-4a92cdb278a1.png)
)

**Comment by paradajz** [comment]
Ah, right. The option has been removed because the code tries to automatically determine the address of the display. Right now the two probed addresses are 0x3C and 0x3D.

**Comment by basst22778** [comment]
![原理图](https://user-images.githubusercontent.com/29714593/185928901-24acd967-89e1-49b4-b8cd-8f34637d6471.png)
OK - then i have the wrong display. 
its 0x78 in the specs.

**Comment by paradajz** [comment]
0x78 is actually 0x3C and should work fine, however, I have run into some displays from eBay that simply do not work at all.
