### ISSUE TITLE
Opendeck M board silk screen wrong label conparing to documentation.

### ISSUE THREAD

**Issue by azgael** [shanteacontrols/OpenDeck#197]
Label on PCB OpenDeck M 2.2 does not match the pin on the buttons input document:
document refers to R1 to R8 on silkscreen of the pcb is written R0 to R7 plus on columns document refers to C1 to C8 on silk screen pins are label C0 to C3 and C5 to C8.
For dummy assembly might be an issue, still not a major one. 
Thanks 
Azgael

**Comment by paradajz** [comment]
Fixed.
